### ISSUE TITLE
Atomicity constraints mean everything will be async?

### ISSUE THREAD

**Issue by dchambers** [dchambers/composerjs#1]
If we don't like the fact that all listeners will effectively be fired asynchronously, we could instead provide a `doTransaction()` method that allows groups of `set()` and `addNode()` invocations to be performed atomically. 

For example:

``` js
doTransaction(function() {
    model.set('some-prop', 'some-value');
    var node = model.nodes.addNode();
    node.set('node-prop', 'node-value');
});
```

This still doesn't require the concept of a _sandbox_ model since the handers never invoke `set()`.

**Comment by james-shaw-turner** [comment]
Yup definitely don't like firing the events asynchronously. Its fiddly but not difficult to program  this using an event cache - I have already implemented this in the  previous "handlers with listeners" version of the composable model.

**Comment by dchambers** [comment]
I've since added a `notifyListeners()` method that would allow tests to be synchronous again, and which could be invoked within debugging sessions to cause the method to be invoked immediately. I consider this issue closed as we now allow synchronous operation too.
