### ISSUE TITLE
Allow genuine circular dependencies to be handled

### ISSUE THREAD

**Issue by dchambers** [dchambers/composerjs#10]
@yasserf has a use case where he has a genuine need for circular dependencies:

> While circular dependencies are certainly to be frowned on, there are instances where it can't really be avoided.
> 
> | Bank (Fixed) | Spread (Can change) | Dealt (can change) |
> | --- | --- | --- |
> | SpotRate | SpotSpread | SpotDealt |
> | ForwardPoints | ForwardSpread | ForwardDealt |
> | OutrightRate | OutrightSpread | OutrightDealt |
> 
> Where if I change spot spread -> spotdealt changes -> outright dealt changes -> outright spread changes -> spotSpread changes (spot spread didn't actually change so it exits loop).
> 
> Now that should be picked up as a circular dependency in theory as if the value derived is not the same as what was entered it would end up looping forever (which has occurred before due to developer error).

How can these be handled?

**Comment by dchambers** [comment]
@yasserf, could you please explain whether `SpotSpread`, `SpotDealt`, `OutrightSpread` & `OutrightDealt` are:
1. Properties that the user can change?
2. Properties that are derived based on other properties?
3. Properties that are sent from a server?
4. Some combination of the above?

**Comment by yasserf** [comment]
1) User can change all non Bank fields
2) All non Bank fields can be derived on other properties (from server and client)
3) Bank fields are always updated by server, and depending on implementation non bank fields can also be updated if user has not edited it.

**Comment by dchambers** [comment]
Thanks @yasserf, that's really useful. Unfortunately I have even more questions now! As it's difficult to have a design conversation using comments, I'll try to contact you when I have to time to see if I can understand this use-case better.

**Comment by yasserf** [comment]
Hey Dom, I'm not actually available in person, still at other job and will be going straight to Japan this weekend! Jan would be a great person to discuss this direct application with, but I'll make sure to keep up to date with comments.

**Comment by dchambers** [comment]
@yasserf, Okay, in that case I'll talk to @janhancic tomorrow, but it would really be good to see a set of derivation arrows for the nine properties you introduce in your use case.

If he's unable to provide that, I might come back with my begging cap later...

**Comment by dchambers** [comment]
Hi @yasserf,

I've spoken to @janhancic and we're struggling to understand how the properties you mention form a circle. Some observations:
- We don't think the _spread_ properties can be changed by the user, but we can see why they might be calculated on the client (from the bid and ask).
- We are guessing that the various _dealt_ currencies relate to the _dealt-currency_, but aren't sure?
- If so, we're not sure why the changing the dealt currency would change the rate. Is this because that might cause the volume band to change, given that 1M Yen is a very different amount to 1M Dollars?

Thanks again, for taking the time to help here.

**Comment by yasserf** [comment]
sorry, terminology might differ.

Bank Rate = Rate that the bank provides (with its own spread and everything)
Spread = The spread the sales user is adding for his own profit
Dealt Rate = The amount the client is willing to pay to make the trade

Spread can be changed by the user, it is what determines how much of a profit margin he has while starting the trade with the client, once he quotes a price the price then locks and the spread is what changes on bank updates to keep dealt price fixed.

spot -> bank  + spread = dealt
forward -> bank + spread = dealt
outright -> bank + spread = dealt

outrightSpread = spotSpread + forwardSpread
outrightDealt = spotDealt + forwardDealt

Event propagation:

Some product owners adjust spot rate when changing outright spread, others change forward, but its general the same flow. In this example we will assume ForwardSpread is what changes.

Forward spread -> ForwardDealt -> OutrightDealt -> OutrightSpread -> Forward spread 

So, the final forward spread calculated should be the same as the one set, which means there isn't a loop. However if the spread is different (due to a bug in calculation which can result in different decimal places or object type) then it keep going round in circles.

This has been seen already when floating point arithmetic was off by a teeny fraction and eventually stopped looping when the spread decreased to zero.

**Comment by dchambers** [comment]
Hi @yasserf,

Thanks again for taking the time to respond, but I'm still struggling to make a circle here. You describe the circle as being this:

> Forward spread -> ForwardDealt -> OutrightDealt -> OutrightSpread -> Forward spread

which involves `OutrightSpread` being defined in terms of `OutrightDealt`, yet you define `OutrightSpread` as:

> outrightSpread = spotSpread + forwardSpread

but this doesn't involve `OutrightDealt`!

I think I've come up with a better notation for describing directed acyclic graphs using text only, and have converted your example to use it, as follows:

```
spot-rate <- S
forward-rate <- S
outright-rate < - S

spot-spread <- U
forward-spread <- U
outright-spread <- spot-spread, forward-spread

spot-dealt <- spot-rate, spot-spread
forward-dealt <- forward-rate, forward-spread
outright-dealt <- spot-dealt, forward-dealt
```

Here, `S` signifies _server_ and `U` signifies _user_. By visually scanning with my eye I can quickly see that there are no circular dependencies here. I've also been thinking about other scenarios that might lead to a circular dependency, and am struggling to find one. In fact, I suspect even if this can occur it's definitely an edge case.

Now, supposing there really are times when this needs to occur, CJS could probably handle it by using a model listener to update the model close the circle. The only issue with this is that listeners would fire when the model is an _in-between_ state, but this already happens with handlers that retrieve their values asynchronously from a server, and we deal with this by setting values to `null` until data becomes available, so something similar might be possible.

Alternatively, we could even build this into the core code if necessary, so instead of having a hander loop that looks like this:

``` js
for(var handler of this.orderedHanders) {
    if(handler.id in handlers) {
        handler();
        handlers.merge(handler.dependentHandlers);
    }
}
```

we could have one that looks something like this, but with extra logic to prevent indefinite looping:

``` js
var circularDependencyEncountered;

do {
    circularDependencyEncountered = false;

    for(var handler of this.orderedHanders) {
        if(handler.id in handlers) {
            handler();
            handlers.merge(handler.dependentHandlers);

            if(handler.hasCircularDependency) {
                circularDependencyEncountered = true;
                break;
            }
        }
    }
} while(circularDependencyEncountered);
```

Unless you think otherwise, I think I'm happy to close this issue for the time being on the basis that there are work arounds if needed, and it looks like an edge case anyway.

**Comment by yasserf** [comment]
There are multiple approaches you can to avoid this issue happening, my argument was that you can't throw an error if a circular dependency is found in those edge cases if it's a real use case.

Perfectly ok with this issue being closed.

PS, just incase this explanation makes more sense.

The data flow is as follows (right hand side is the data that is derived (out), left hand side are the fields used to listen for updates (in) ).

When I change the Forward Spread:

FR + FS = FD (my dealt forward changes)
SR + FR = OD (my outright dealt changes)
OD - OR = OS (my outright spread changes)
OS - SR = FS (it tries to update my outright forward again)

**Comment by dchambers** [comment]
Hi @yasserf,

Thanks for the very clear use case. As it happens I've actually now thought of an even better way to solve this by introducing a `beforechange` event on the entire model. This would allow a listener to be notified before the `change` and `mutation` listeners have been notified, allowing such a listener to invoke `set()` if needed, to force another round of handler processing.

I'll update the site docs in due course and close this issue.

**Comment by dchambers** [comment]
Okay, this has now been fixed.
