### ISSUE TITLE
DISCUSSION: RatesHandler example and the pending state

### ISSUE THREAD

**Issue by dchambers** [dchambers/composerjs#12]
@janhancic / @james-shaw-turner: I've added a simplified [rates handler example](https://github.com/dchambers/composerjs/blob/master/code-examples/rate-handler/RateHandler.js), which was possible by adding two new features:
1. The ability for handlers to provide a `dispose()` method if they need to perform any resource de-allocation.
2. The ability for handlers to return `false` if they are currently unable to provide their _output-properties_.

This second point has reminded me of another huge bug vector we encounter with these kinds of models, where the model is in an incoherent state due to the fact that some properties have changed, yet we are temporarily unable to provide matching derived properties.

This, I believe this has revealed another major advantage to CJS over CM, in that the CM model requires the entire composable model (including other handlers that have no knowledge of the handlers they've been composed with) to do the right thing when the model is an incoherent state, yet with CJS we can ban all model mutation when this happens, so that these subtle bugs can never occur.

Of course " ban[ning] all model mutation when this happens" sounds drastic, but it is made manageable by providing a `ready` call-back that can be used to wrap external model mutation for models that are able to get into this state.

This is discussed in more depth in the [Emitted Events](https://github.com/dchambers/composerjs#emitted-events) section.

**Comment by james-shaw-turner** [comment]
We need to go through some specific scenarios to clarify what you mean by "incoherent state". Lets get around a whiteboard.

**Comment by dchambers** [comment]
Closing as after speaking with the team we found a much simpler way to deal with this issue that also doesn't affect compsability &mdash; handlers now simply set output properties to `null` if they can't provide a value.
