### ISSUE TITLE
DISCUSSION: CM versus CJS: Derivation versus Listeners

### ISSUE THREAD

**Issue by james-shaw-turner** [dchambers/composerjs#13]
Just wanted to separate this discussion onto a separate issue to make it easier to follow:
## CM handler listens to fields

``` JavaScript
var Subscriber = require("./Subscriber");
/* field definitions omitted */
function Handler() {
};

Handler.prototype.init = function(model){
    var subscriber = new Subscriber();
    model.onDestroy(function(){
        subscriber.unsubscribe();
        model.off("*");
    });

    var subscribe = function(currency){
        //assume subscriber releases any old subscription
        subscriber.subscribe(currency, function(rate){
            model.set("rate", rate);
        });
     });
     model.on("change:Currency", function(currency){
         model.set("rate", null);
         subscribe(currency)
     });
     subscribe(model.get("Currency"));
};
```
## CJS handler is called with property maps

``` JavaScript

var Subscriber = require('./Subscriber');

function RateHandler(fieldMap) {
  fieldMap = fieldMap || {};

  var handler = function(in, out) {
    out.rate = null;

    subscriber.requestSubject('/FX/' + in.currencyPair + '/' + in.tenor + '/' + in.baseCurrency + '/' + in.amount, function(data) {
      out.rate = data.rate;
      out.hasBeenUpdated();
    });
  };

  handler.dispose = function() {
    subscriber.dispose();
  };
```
## Pros & Cons
1. CJS removes the need to manage field listeners. Although its easy enough to remove all listeners with a little syntatic sugar: `model.off("*");` This can be removed altogether if the model auto-magically calls this before `destroy()` is called.
2. CJS will send you an entire map of the defined input properties, even if only one property has changed. CM allows you to listen for changes on individual fields. If that's important,  the handler has to implement its own dirty checking by caching old values.
3. Conversely in CM when multiple inputs change, listeners fire multiple times: e.g. in the case of a subscription that depends on currency and tenor you might end up re-subscribing twice. CJS will only call the `handle()` method once.
4. CM fixes the dependency DAG at `seal()` time. CJS allows you to add and remove listeners as you want. For example in a particular 'trade status' you might want to 'disable' a handler. In CJS you would do an `if` check on the 'trade status' variable every time and do nothing. In CM you add/remove listeners when the state field changes. This makes the code more readable for steady state conditions. Simply look at the `if` statement. However if a change in state triggers an action - e.g. change a subscription, then the handler must cache the "old" value (for comparison to recognise change) and only re-subscribe on change.
5. In CM you can add the same instance of a Handler to two models, listening on one and updating another. This allows more flexibility designing screens. Would CJS allow this?
6. Implementation: in CJS we can use existing `Emitr` library for all observable behaviour. We would have to write a DAG analyser for CJS.
7. Supporting circular dependencies kills the CJS proposal. Sorry: no it doesn't. The derivation manager needs coded to stop processing if handlers don't dirty fields.
8. In CJS a DAG analyser allows us to detect circular dependencies at `seal()` time. We could throw an error or configure circularity as being allowed.
9. CM has a clean lifecycle initialisation - `init()` is called immediately after `seal()` when we know all fields are at their proper starting values. In CJS all `handler()` methods must also be called after `seal()` to allow initialisation at the correct time. However the method must be coded in such a way as to only create resources the first time it runs. The initialisation and derivation code are overloaded into the same method. Explicitly "separating concerns" as CM does is advantageous.
10. Debugging the callstack in CJS should probably be easier  because the callstack for cascaded updates wont go in and out of the `Emitr` observable infrastructure
11. Debugging could be more difficult in CJS because you can only see the state of the properties passed to you and not the state of the whole model.
12. However if the handler does have access to all the properties in the model then the developer can screw up and update or listen to undeclared fields (you win some you lose some!). CM can be coded (or made configurable) to only provide requested fields in a model sandbox.

**Comment by dchambers** [comment]
Hi @james-shaw-turner, comments in line:

> 1. CJS removes the need to manage field listeners. Although its easy enough to remove all listeners with a little syntatic sugar: `model.off("*");` This can be removed altogether if the model auto-magically calls this before `destroy()` is called.

Auto-magically invoking `model.off("*");` would help, but CM handlers would still need to:
1. Add a listener to all node-lists for mutation.
2. Add a listener for all newly added nodes.

A node-list that contains a node-list would be particular gnarly in CM, since you'd need to both subscribe and un-subscribe to mutation events within the sub node-lists, on top of the change based subscription code for the items at both levels.

> 1. CJS will send you an entire map of the defined input properties, even if only one property has changed. CM allows you to listen for changes on individual fields. If that's important,  the handler has to implement its own dirty checking by caching old values.

Not entirely true anymore since handlers now receive a map of the previous values, so no need for handlers to cache values themselves. Furthermore, I question the need for dirty checking in the first place since derivations should involve all input-properties anyway, so that the atomic operation the handler is performing must be re-performed if any of the input properties change anyway.

> 1. Conversely in CM when multiple inputs change, listeners fire multiple times: e.g. in the case of a subscription that depends on currency and tenor you might end up re-subscribing twice. CJS will only call the `handle()` method once.

True.

> 1. CM fixes the dependency DAG at `seal()` time. CJS allows you to add and remove listeners as you want. For example in a particular 'trade status' you might want to 'disable' a handler. In CJS you would do an `if` check on the 'trade status' variable every time and do nothing. In CM you add/remove listeners when the state field changes. This makes the code more readable for steady state conditions. Simply look at the `if` statement. However if a change in state triggers an action - e.g. change a subscription, then the handler must cache the "old" value (for comparison to recognise change) and only re-subscribe on change.

This last sentence isn't true since the handler will never be invoked unless one of the input properties has changed, as I'm purposely not supporting non-determenistic handlers. Additionally, the cache of old values is passed to the handler now too.

> 1. In CM you can add the same instance of a Handler to two models, listening on one and updating another. This allows more flexibility designing screens. Would CJS allow this?

You can do this in CJS too.

> 1. Implementation: in CJS we can use existing `Emitr` library for all observable behaviour. We would have to write a DAG analyser for CJS.

Having to "write a DAG analyser" is a bit strong given that it's about ten lines of code.

> 1. Supporting circular dependencies kills the CJS proposal. Sorry: no it doesn't. The derivation manager needs coded to stop processing if handlers don't dirty fields.

Not anymore. CJS now has a super neat solution to the circular dependency problem that involves use of a new `beforechange` event.

> 1. In CJS a DAG analyser allows us to detect circular dependencies at `seal()` time. We could throw an error or configure circularity as being allowed.

True, and in fact we'd always throw an error.

> 1. CM has a clean lifecycle initialisation - `init()` is called immediately after `seal()` when we know all fields are at their proper starting values. In CJS all `handler()` methods must also be called after `seal()` to allow initialisation at the correct time. However the method must be coded in such a way as to only create resources the first time it runs. The initialisation and derivation code are overloaded into the same method. Explicitly "separating concerns" as CM does is advantageous.

This is a straw-man argument, since a comparison of the rate-handler in both CM and CJS shows that the CJS version is far simpler and easier to understand.

> 1. Debugging the callstack in CJS should probably be easier  because the callstack for cascaded updates wont go in and out of the `Emitr` observable infrastructure

True.

> 1. Debugging could be more difficult in CJS because you can only see the state of the properties passed to you and not the state of the whole model.

This isn't necessarily true. Although I was planning to prevent invocation of the public API methods while the handlers are being run to prevent handlers using them, there's no intrinsic reason these can't be invoked, and I'm sure I can imagine a way of allowing developers to do this for debugging purposes.

> 1. However if the handler does have access to all the properties in the model then the developer can screw up and update or listen to undeclared fields (you win some you lose some!). CM can be coded (or made configurable) to only provide requested fields in a model sandbox.

True.

**Comment by dchambers** [comment]
The issue with developers not being able to introspect the model while debugging handlers has now been fixed &mdash; see the updated [Atomicity](https://github.com/dchambers/composerjs#atomicity) section.

**Comment by dchambers** [comment]
Closing as this discussion is now coming to an end as consensus has broadly been reached.
