### ISSUE TITLE
Clarification  of Handler inputs array for nodelist containing different shaped nodes?

### ISSUE THREAD

**Issue by james-shaw-turner** [dchambers/composerjs#25]
@dchambers 

> When used as an input-property for a handler, the the handler receives an array containing the values for all nodes within the node-list, for example:

What appears in the array of different shaped nodes. e.g.

N1 has properties:  foo and bar
N2 has properties:  foo
N3 has properties:  foo and bar

I add a handler to the nodelist that defines "bar" as an input field
I assume you get an array off 3 value maps. The map for the second node is simply missing "bar" property.

**Comment by dchambers** [comment]
It really depends on what you want. The model you've described can be created like this:

``` js
model.addNodeList('nodes');
model.nodes.set('foo', true);
model.nodes('extended').set('bar', true);
// handler to be added here
model.seal();

model.nodes.addNode('extended');
model.nodes.addNode();
model.nodes.addNode('extended');
```

in which case you can add your `handler` like this if you want it to see all nodes:

``` js
model.nodes.addHandler([], ['foo'], handler);
```

or like this if you only want it to see the nodes that have both the `foo` and `bar` properties:

``` js
model.nodes('extended').addHandler([], ['foo', 'bar'], handler);
```

Finally, it's worth pointing out that trying to register for both `bar` and `foo` on all nodes would cause an error to be thrown, for example:

``` js
model.nodes.addHandler([], ['foo', 'bar'], handler); // this line will error
```

**Comment by james-shaw-turner** [comment]
@dchambers 
That precludes me from writing a handler that wants to look at all instances in a nodelist and do different behaviour dependent on the (non)existence of "bar".  That is too restrictive.

**Comment by dchambers** [comment]
Okay, good point. Let's instead allow this and put the onus on the developer to do the right thing, for example:

``` js
model.nodes.addHandler([], ['foo', 'bar'], function(input, output, current, index) {
  if(model.nodes.item(index).nodeType == 'extended') {
    output.bar = 'Hello!';
  }
});
```

or even this since `output.bar` would be ignored anyway for nodes that don't have that property:

``` js
model.nodes.addHandler([], ['foo', 'bar'], function(input, output, current, index) {
  output.bar = 'Hello!';
});
```

**Comment by dchambers** [comment]
Closing this as I've updated to the documentation to provide clarification of the behaviour here.
