### ISSUE TITLE
Handler input definition line confusing

### ISSUE THREAD

**Issue by james-shaw-turner** [dchambers/composerjs#26]
@dchambers
In the TicketModel.js example code there is the following line

``` JavaScript
bidRateHandler.inputs =composerjs.props(bidRateHandler.inputs).relativeTo(this).excluding('currencyPair');
```

I don't think that the meaning of this is very intuitive.

**Comment by dchambers** [comment]
`TicketModel.js`, and all other code examples,  no longer reflect the current API. Additionally, `relativeTo()` not being intuitive was one of the feedback items from @janhancic in Monday's review session, and was fixed as a consequence of the relative _property-specifier_ work that was done to support recursion.

I'll add a comment to this issue once the code examples have been updated, so you can verify you are happy with the new syntax.

**Comment by dchambers** [comment]
@james-shaw-turner, I've updated [TicketModel](https://github.com/dchambers/composerjs/blob/master/code-examples/fx-ticket/TicketModel.js) to use that latest model APIs. Do you want to see if it's easier to comprehend now?

**Comment by dchambers** [comment]
@james-shaw-turner, I'm closing this issue. Feel free to re-open if you don't think it's been fixed.
